import "../styles/globals.css";
import WrapperBetweenContainer from "../components/ui/containers/FlexBetweenContainer";
import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import { UserContextProvider } from "../store/UserContext";

function MyApp({ Component, pageProps }) {
  return (
    <WrapperBetweenContainer>
      <Head>
        <title>Restaurant Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </WrapperBetweenContainer>
  );
}

export default MyApp;
